[project]
name = "Mem0_MemoryClient_REST_API_Server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "mem0ai>=0.1.109",
    "python-dotenv>=1.1.0",
]
